### PR TITLE
Try to fix the passing variable problem

### LINKED ISSUE #16: it is not fully supported when passing variable as parameter to ejs include function
**Describe the bug**

I am not sure if this should be regarded as a bug.
I found this problem last week, this happened when I used `include` within a `for` or `forEach` loop in `ejs`, just like this:

````ejs
<%
  const fs = require('fs');
   fs.readdirSync('./src/ejs-partial').forEach((filename)=>{ %>
   
   <% const filePath = `src/${filename}`%>

   <%- include(filePath)%>

  <%
   }) 
%>
````

the problem was that webpack devserver did not recognize those partial ejs files as dependency, and I thought I could tell the reason, bc we were actually using regex to detect all `include` function inside `ejs` files, which means passing variable  to `include` function is not fully supported.

But I still have no idea how to fix this..., I saw there was a `includer` option in the ejs npm package, which is capable of customize the original `include` function , but I am not sure If using `includer` is a good way to go. (gonna need a test for this I guess :( )

> includer Custom function to handle EJS includes, receives (originalPath, parsedPath) parameters, where originalPath is the path in include as-is and parsedPath is the previously resolved path. Should return an object { filename, template }, you may return only one of the properties, where filename is the final parsed path and template is the included content.

https://www.npmjs.com/package/ejs

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

- OS: [e.g. macOS 10.15.7]
- node.js: [e.g. 16.0.0]

I guess it is all version :/

**Additional context**

### PR DESCRIPTION
**Pull request by mizok**
# Description

> Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

@dc7290 

I tried the solution I mentioned in #16 (using customized `includer` function).
And things seem to work without problem(I am not very sure if this will cause any side effect or problem, 'cause I still don't have time for a full-test.)

but THIS did work:
img
result:
img

And bc  it is gonna be a big change(if you think this solution is ok), I guess it should be checked carefully.

fix #16 

## Type of change

> Please delete options that are not relevant.

- [V ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Bug fix I guess.

# How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

I forked this repo, change `index.ts` then run `build`, then copy paste all the built library to the `node_modules` in my testing repo.

# Checklist:

- [V] My code follows the style guidelines of this project
- [V] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [V] My changes generate no new warnings

### CODE REVIEW

**Comment by dc7290** [comment]
@mizok 
#16 can `include`, but updating the file will not be reflected.
Is that correct?

**Comment by mizok** [comment]
@dc7290  I guess you missed this?

devServer: {
    
    watchFiles: ['*.html', 'src/template/*.html', '*.ejs', 'src/template/*.ejs','src/template/**/*.ejs'],  // this is important

  },
  
  You will have to watch all your file if that is going to be dependency

**Comment by mizok** [comment]
> @mizok Did I understand #16 correctly that you can include ejs files, but they are not recognized as webpack dependencies? If so, does this solution update the webpack dependencies?

You can check my change , I thought I did add 
````
this.addDependency(parsedPath);
````
I guess it's line 93 or some what :/

**Comment by mizok** [comment]
> @mizok 
> 

> If so, does this solution update the webpack dependencies?

Yap ,it does.

**Comment by dc7290** [comment]
@mizok 
I'm impressed!
The idea of using `customIncluder` as a way to add dependencies to webpack was an eye opener.

As for the code formatting, I would like to see a slight modification, so please just do that.

**Comment by dc7290** [comment]
@mizok 
Try running the following command again.
```bash
yarn
```
Then `husky` will be installed and will automatically lint and format the file before committing it.

**Comment by mizok** [comment]
> @mizok Try running the following command again.
> 
> ```shell
> yarn
> ```
> 
> Then `husky` will be installed and will automatically lint and format the file before committing it.

ok sure :D

**Comment by mizok** [comment]
> @mizok Try running the following command again.
> 
> ```shell
> yarn
> ```
> 
> Then `husky` will be installed and will automatically lint and format the file before committing it.

Cool, I have

**Comment by mizok** [comment]
@dc7290 

OK, I guess the lint things are done already, just check it.

**Comment by dc7290** [comment]
@mizok 
Nice!

**Pull request merged**
